[project]
name = "repaso-python"
version = "0.1.0"
description = "Entorno de laboratorio para el repaso de Python aplicado a imagenes como datos"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "matplotlib",
    "pillow",
    "gradio",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
