[project]
name = "computer-vision-parte-1"
version = "0.1.0"
description = "Entorno de laboratorio para vision por computadora con OpenCV (parte 1)"
requires-python = ">=3.12"
dependencies = [
    "matplotlib",
    "numpy",
    "opencv-python",
    "pillow",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
